name: Publish to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set Git user
        run: |
          git config --global user.email "brad50916@gmail.com"
          git config --global user.name "Tien-Hung Hsiao"

      - name: Build Project
        run: |
          pnpm install
          pnpm run build
          pnpm run deploy