name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user
        run: |
          git config --global user.email "brad50916@gmail.com"
          git config --global user.name "Tien-Hung Hsiao"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Project
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          pnpm run deploy 