name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Project
        run: |
          pnpm install
          pnpm run build
          pnpm run deploy