name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Project
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Configure Git to use the PAT for authentication
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
          # Clone the gh-pages branch (or create it if it doesn't exist)
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || (echo "Cloning failed; initializing new branch." && mkdir gh-pages && cd gh-pages && git init && git remote add origin https://github.com/${{ github.repository }})

          # Copy the build output to the gh-pages branch
          cp -r dist/* gh-pages/

          # Navigate to the gh-pages directory
          cd gh-pages

          # Add, commit, and push changes
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin gh-pages